[package]
name = "exante"
version = "0.1.0"
edition = "2021"
authors = ["Daniel Semkowicz <daniel@semkowicz.pl>"]
license = "MIT OR Apache-2.0"
description = "HTTP client for Exante REST API version 3.0"

[dependencies]
